docs_dir: doc/book
site_dir: doc/html
pages:
    - index.md
    - Usage: usage.md
site_name: zend-debug
site_description: zend-debug
repo_url: 'https://github.com/zendframework/zend-debug'
copyright: 'Copyright (c) 2016 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
